FROM python:3.6
RUN pip3 install --no-cache-dir \
       datascience \
       nbconvert \
       jupyter_client \
       ipykernel \
       matplotlib \
       pandas \
       ipywidgets \
       scipy \
       gofer-grader==1.0.3
