#!/bin/bash
export PATH=/root/miniforge3/bin:$PATH:/root/.TinyTeX/bin/x86_64-linux
eval "$(mamba shell hook --shell bash)"
mamba activate {{ otter_env_name }}
python {{ autograder_dir }}/source/run_otter.py
