name: otter-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyter_server
  - c-compiler
  - cxx-compiler
  - zlib
  - r-base=4.5.*
  - r-devtools
  - r-essentials
  - r-gert
  - r-rmarkdown
  - r-quarto
  - r-startup
  - r-stringi
  - r-testthat
  - r-usethis
  - r-ottr==1.6.0
  - rpy2
  - pip:
      - otter-grader[grading,plugins]==7.0.0
